<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Bases\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookmark.Entities\Bookmark.Entities.csproj" />
  </ItemGroup>

</Project>
